### ISSUE TITLE
slacker vs slackclient

### ISSUE THREAD

**Issue by ghostsquad** [scrapinghub/slackbot#107]
I'm curious why this is using the `Slacker` library + websockets instead of the `Slackclient` library. The websocket code here seems to have a bit of code redundancy to `Slackclient`. Can you shed some light? Not necessarily saying there's anything wrong with it, just wondering if there are some benefits you've gained by not using `Slackclient`.

**Comment by jtatum** [comment]
If you're referring to https://github.com/slackapi/python-slackclient, despite being out for over a year, still doesn't support Python 3. The pace of development on it has been slow, with 6 releases since the initial release. Slacker, by comparison, is on its 48th release. Finally, slackclient still uses the same websocket-client library inside. I didn't make the initial choice but if I was developing a bot today I'd go the same route until something changes with the official library.
