### ISSUE TITLE
SlackBot doesn't respond to messages according to custom plugin

### ISSUE THREAD

**Issue by ghsatpute** [scrapinghub/slackbot#69]
I am following procedure given [here](https://github.com/lins05/slackbot)

I created `mybot.py` and added below code

```
...
@respond_to('hi', re.IGNORECASE)
def hi(message):
    message.reply('I can understand hi or HI!')
    # react with thumb up emoji
    message.react('+1')
...
```

I have added this plugin to file by `run_settings.py`

```
PLUGINS = [
    'slackbot.plugins',
    'mybot',
]
```

After I run bot by `python run.py` I can see my bot coming online. But when I message it "hi", it returns default message not the correct reply. 

What am I missing here?

**Comment by jtatum** [comment]
Bot settings should be in a file named slackbot_settings.py. I think you actually put them there and just made a typo in this report, but I wanted to make it explicit in this comment.

The plugin import code currently expects a package containing plugins rather than a single importable module. You'd have to make a subdirectory named mybot and put that code in a module:

```
$ mkdir mybot
$ mv mybot.py mybot/hi.py
$ touch mybot/__init__.py
$ rm mybot.pyc
```

I'm submitting a PR to allow it to accept a single importable module as well.

**Comment by ghsatpute** [comment]
Thanks @jtatum. This would be great.
